[TASK] Clean up dist archive
TYPO3/Fluid pull request #403
Opened 2018-08-08 07:34 UTC by mbrodala

Do not export files/directories which are not necessary for production usage.

Fixes #402

2018-08-23 09:43 UTC, NamelessCoder commented
Please leave this one open for a little while (more to come).

2021-03-22 12:09 UTC, NamelessCoder requested changes
Adjust to not exclude:

* doc
* examples
* tests(/Unit/ViewHelpers/BaseViewHelperTestCase.php)
* tests(/Unit/UnitTestCase.php)
* tests(/Unit/BaseTestCase.php)

(either ship all of tests/ or exclude but manually include the three mentioned files for shipping)

Then this will be accepted ;)

2021-03-22 14:03 UTC, mbrodala commented
@NamelessCoder OK, the export rules where adjusted:

<details>

```
$ git archive HEAD -o export.zip
$ zipinfo -1 export.zip 
LICENSE.txt
MAINTAINERS
README.md
bin/
bin/fluid
composer.json
doc/
doc/FLUID_CREATING_VIEWHELPERS.md
doc/FLUID_EXPRESSIONS.md
doc/FLUID_IMPLEMENTATION.md
doc/FLUID_STRUCTURE.md
doc/FLUID_SYNTAX.md
doc/FLUID_VIEWHELPERS.md
doc/README.md
doc/README_TYPO3.md
examples/
examples/ResourceOverrides/
examples/ResourceOverrides/Private/
examples/ResourceOverrides/Private/Layouts/
examples/ResourceOverrides/Private/Layouts/Default.html
examples/ResourceOverrides/Private/Partials/
examples/ResourceOverrides/Private/Partials/SecondPartial.html
examples/ResourceOverrides/Private/Templates/
examples/ResourceOverrides/Private/Templates/Default/
examples/ResourceOverrides/Private/Templates/Default/Default.html
examples/Resources/
examples/Resources/Private/
examples/Resources/Private/Layouts/
examples/Resources/Private/Layouts/Default.html
examples/Resources/Private/Layouts/Default.json
examples/Resources/Private/Layouts/Dynamic.html
examples/Resources/Private/Partials/
examples/Resources/Private/Partials/EscapingModifierPartial.html
examples/Resources/Private/Partials/FirstPartial.html
examples/Resources/Private/Partials/SecondPartial.html
examples/Resources/Private/Partials/Structures.html
examples/Resources/Private/Singles/
examples/Resources/Private/Singles/CacheStatic.html
examples/Resources/Private/Singles/CacheWarmup.html
examples/Resources/Private/Singles/Conditions.html
examples/Resources/Private/Singles/CustomResolving.html
examples/Resources/Private/Singles/DynamicLayout.html
examples/Resources/Private/Singles/ErrorHandling.html
examples/Resources/Private/Singles/EscapingModifier.html
examples/Resources/Private/Singles/LayoutLess.html
examples/Resources/Private/Singles/Math.html
examples/Resources/Private/Singles/NamespaceResolving.html
examples/Resources/Private/Singles/Namespaces.html
examples/Resources/Private/Singles/Passthrough.html
examples/Resources/Private/Singles/Single.html
examples/Resources/Private/Singles/Structures.html
examples/Resources/Private/Singles/VariableProvider.html
examples/Resources/Private/Singles/Variables.html
examples/Resources/Private/Templates/
examples/Resources/Private/Templates/Default/
examples/Resources/Private/Templates/Default/Default.html
examples/Resources/Private/Templates/Default/Nested/
examples/Resources/Private/Templates/Default/Nested/Default.html
examples/Resources/Private/Templates/Default/OtherFormat.json
examples/Resources/Private/Templates/Other/
examples/Resources/Private/Templates/Other/Default.html
examples/Resources/Private/Templates/Other/List.html
examples/cache/
examples/cache/.keep
examples/example_cachestatic.php
examples/example_cachewarmup.php
examples/example_conditions.php
examples/example_customresolving.php
examples/example_dynamiclayout.php
examples/example_errorhandling.php
examples/example_escapingmodifier.php
examples/example_format.php
examples/example_layoutless.php
examples/example_math.php
examples/example_multiplepaths.php
examples/example_mvc.php
examples/example_namespaceresolving.php
examples/example_namespaces.php
examples/example_passthrough.php
examples/example_single.php
examples/example_structures.php
examples/example_variableprovider.php
examples/example_variables.php
examples/include/
examples/include/class_customvariableprovider.php
examples/include/class_customviewhelper.php
examples/include/class_customviewhelperresolver.php
examples/include/view_init.php
src/
src/Component/
src/Component/Argument/
src/Component/Argument/ArgumentCollection.php
src/Component/ComponentInterface.php
src/Core/
src/Core/Cache/
src/Core/Cache/FluidCacheInterface.php
src/Core/Cache/FluidCacheWarmerInterface.php
src/Core/Cache/FluidCacheWarmupResult.php
src/Core/Cache/SimpleFileCache.php
src/Core/Cache/StandardCacheWarmer.php
src/Core/Compiler/
src/Core/Compiler/AbstractCompiledTemplate.php
src/Core/Compiler/FailedCompilingState.php
src/Core/Compiler/NodeConverter.php
src/Core/Compiler/StopCompilingChildrenException.php
src/Core/Compiler/StopCompilingException.php
src/Core/Compiler/TemplateCompiler.php
src/Core/Compiler/UncompilableTemplateInterface.php
src/Core/Compiler/ViewHelperCompiler.php
src/Core/ErrorHandler/
src/Core/ErrorHandler/ErrorHandlerInterface.php
src/Core/ErrorHandler/StandardErrorHandler.php
src/Core/ErrorHandler/TolerantErrorHandler.php
src/Core/Exception.php
src/Core/Parser/
src/Core/Parser/BooleanParser.php
src/Core/Parser/Configuration.php
src/Core/Parser/Exception.php
src/Core/Parser/Interceptor/
src/Core/Parser/Interceptor/Escape.php
src/Core/Parser/InterceptorInterface.php
src/Core/Parser/ParsedTemplateInterface.php
src/Core/Parser/ParsingState.php
src/Core/Parser/PassthroughSourceException.php
src/Core/Parser/Patterns.php
src/Core/Parser/SyntaxTree/
src/Core/Parser/SyntaxTree/AbstractNode.php
src/Core/Parser/SyntaxTree/ArrayNode.php
src/Core/Parser/SyntaxTree/BooleanNode.php
src/Core/Parser/SyntaxTree/EscapingNode.php
src/Core/Parser/SyntaxTree/Expression/
src/Core/Parser/SyntaxTree/Expression/AbstractExpressionNode.php
src/Core/Parser/SyntaxTree/Expression/CastingExpressionNode.php
src/Core/Parser/SyntaxTree/Expression/ExpressionException.php
src/Core/Parser/SyntaxTree/Expression/ExpressionNodeInterface.php
src/Core/Parser/SyntaxTree/Expression/MathExpressionNode.php
src/Core/Parser/SyntaxTree/Expression/ParseTimeEvaluatedExpressionNodeInterface.php
src/Core/Parser/SyntaxTree/Expression/TernaryExpressionNode.php
src/Core/Parser/SyntaxTree/NodeInterface.php
src/Core/Parser/SyntaxTree/NumericNode.php
src/Core/Parser/SyntaxTree/ObjectAccessorNode.php
src/Core/Parser/SyntaxTree/RootNode.php
src/Core/Parser/SyntaxTree/TextNode.php
src/Core/Parser/SyntaxTree/ViewHelperNode.php
src/Core/Parser/TemplateParser.php
src/Core/Parser/TemplateProcessor/
src/Core/Parser/TemplateProcessor/EscapingModifierTemplateProcessor.php
src/Core/Parser/TemplateProcessor/NamespaceDetectionTemplateProcessor.php
src/Core/Parser/TemplateProcessor/PassthroughSourceModifierTemplateProcessor.php
src/Core/Parser/TemplateProcessorInterface.php
src/Core/Parser/UnknownNamespaceException.php
src/Core/Rendering/
src/Core/Rendering/AbstractRenderable.php
src/Core/Rendering/RenderableClosure.php
src/Core/Rendering/RenderableInterface.php
src/Core/Rendering/RenderingContext.php
src/Core/Rendering/RenderingContextInterface.php
src/Core/Rendering/StandardRenderable.php
src/Core/Variables/
src/Core/Variables/ChainedVariableProvider.php
src/Core/Variables/JSONVariableProvider.php
src/Core/Variables/StandardVariableProvider.php
src/Core/Variables/VariableExtractor.php
src/Core/Variables/VariableProviderInterface.php
src/Core/ViewHelper/
src/Core/ViewHelper/AbstractConditionViewHelper.php
src/Core/ViewHelper/AbstractTagBasedViewHelper.php
src/Core/ViewHelper/AbstractViewHelper.php
src/Core/ViewHelper/ArgumentDefinition.php
src/Core/ViewHelper/Exception.php
src/Core/ViewHelper/TagBuilder.php
src/Core/ViewHelper/Traits/
src/Core/ViewHelper/Traits/CompileWithContentArgumentAndRenderStatic.php
src/Core/ViewHelper/Traits/CompileWithRenderStatic.php
src/Core/ViewHelper/Traits/ParserRuntimeOnly.php
src/Core/ViewHelper/ViewHelperInterface.php
src/Core/ViewHelper/ViewHelperInvoker.php
src/Core/ViewHelper/ViewHelperResolver.php
src/Core/ViewHelper/ViewHelperVariableContainer.php
src/Exception.php
src/View/
src/View/AbstractTemplateView.php
src/View/AbstractView.php
src/View/Exception.php
src/View/Exception/
src/View/Exception/InvalidSectionException.php
src/View/Exception/InvalidTemplateResourceException.php
src/View/TemplatePaths.php
src/View/TemplateView.php
src/View/ViewInterface.php
src/ViewHelpers/
src/ViewHelpers/AliasViewHelper.php
src/ViewHelpers/Cache/
src/ViewHelpers/Cache/DisableViewHelper.php
src/ViewHelpers/Cache/StaticViewHelper.php
src/ViewHelpers/Cache/WarmupViewHelper.php
src/ViewHelpers/CaseViewHelper.php
src/ViewHelpers/CommentViewHelper.php
src/ViewHelpers/CountViewHelper.php
s [...]

2021-03-22 14:07 UTC, NamelessCoder approved these changes

2021-03-22 14:08 UTC, merged