[BUGFIX] Restore support for data- prefixed arguments
TYPO3/Fluid pull request #528
Opened 2020-10-31 12:08 UTC by NamelessCoder

Due to a regression in https://github.com/TYPO3/Fluid/pull/419,
a TagBasedViewHelper which was called with one or more
data- prefixed arguments would discard the prefixed arguments
and the output would not contain the attribute.

This patch fixes that regression by moving the handling of
unregistered arguments to the initialize() function in order
to make sure the additional attributes are handled *after*
the reset() method has been called on TagBuilder.

References: #419

2021-01-26 16:18 UTC, mbrodala commented
@NamelessCoder Can you rebase this one? I guess #530 will need to be adjusted if merged after this one.

2021-01-27 11:09 UTC, NamelessCoder commented
@mbrodala Done, but please wait for Travis to complete - I wasn't able to run unit tests locally and I'm a bit busy on other projects. Yep, #530 will need an adjustment afterwards!

2021-01-27 13:32 UTC, mbrodala requested changes
Should I add this test?

2021-01-27 13:32 UTC, mbrodala commented on tests/Functional/Cases/TagBasedTest.php
> +}
We should add one additional test here which passes in *both* `'data-foo'` and `'data' => ['foo' => ...]` to clearly document the expected result for such a conflict.

2021-01-27 14:19 UTC, NamelessCoder commented
> Should I add this test?

That would be great, thanks!

2021-01-27 15:41 UTC, mbrodala approved these changes

2021-04-22 06:38 UTC, mbrodala commented
@NamelessCoder I'd merge this now if you don't see anything missing since it predates #530

2021-04-22 07:25 UTC, NamelessCoder commented
@mbrodala All good from my perspective!

2021-04-22 07:38 UTC, merged